### ISSUE TITLE
size mismatch error in model_docsum.py in tf.concat

### ISSUE THREAD

**Issue by azadFKM** [EdinburghNLP/Refresh#35]
hi shashi 
i have a problem here on both cnn and dailymail datasets
in running them both i keep getting the following error
i would appreciate your help

cuda version  >>> release 10.0, V10.0.130
tensorflow  >>>  tensorflow-gpu = 1.14.0

Traceback (most recent call last):
  File "document_summarizer_training_testing.py", line 282, in <module>
    tf.app.run()
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "document_summarizer_training_testing.py", line 277, in main
    train()
  File "document_summarizer_training_testing.py", line 102, in train
    model = MY_Model(sess, len(vocab_dict)-2)
  File "/home/azad/Documents/Refresh-master/my_model.py", line 58, in __init__
    self.extractor_output, self.logits = model_docsum.policy_network(self.vocab_embed_variable, self.document_placeholder, self.label_placeholder)
  File "/home/azad/Documents/Refresh-master/model_docsum.py", line 142, in policy_network
    fullvocab_embed_variable = tf.concat(0, [pad_embed_variable, unk_embed_variable, vocab_embed_variable])
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1296, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1087, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1145, in convert_to_tensor_v2
    as_ref=False)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1145, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1095, in _autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5897, in pack
    "Pack", values=values, axis=axis, name=name)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2027, in __init__
    control_input_ops)
  File "/home/azad/anaconda3/envs/thesis/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 559183. Shapes are [1,200] and [559183,200].
	From merging shape 1 with other shapes. for 'PolicyNetwork/concat/concat_dim' (op: 'Pack') with input shapes: [1,200], [1,200], [559183,200].

**Comment by MousaMohammed** [comment]
@azadFKM did you figure it out? I'm getting the same error!
